title: 基于卷积神经网络识别金融票据中的数字串
description: Recognize the number strings in financial bills based on CNN(Convolutional Neural Network)
show_downloads: true
google_analytics: UA-139329336-2
theme: jekyll-theme-slate